### ISSUE TITLE
undefined symbol: __fatbinwrap_38_cuda_device_runtime_compute_75_cpp1_ii_8b1a5d37

### ISSUE THREAD

**Issue by SparkJiao** [facebookresearch/bitsandbytes#12]
```
(torch1.8-py3.8) jiaofangkai@dell-PowerEdge-T640:/home/share/jiaofangkai$ python check_bnb_install.py
Traceback (most recent call last):
  File "check_bnb_install.py", line 1, in <module>
    import bitsandbytes as bnb
  File "/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 5, in <module>
    from .optim import adam
  File "/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 5, in <module>
    from .adam import Adam, Adam8bit, Adam32bit
  File "/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/site-packages/bitsandbytes/optim/adam.py", line 6, in <module>
    from bitsandbytes.optim.optimizer import Optimizer2State
  File "/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/site-packages/bitsandbytes/optim/optimizer.py", line 6, in <module>
    import bitsandbytes.functional as F
  File "/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/site-packages/bitsandbytes/functional.py", line 13, in <module>
    lib = ct.cdll.LoadLibrary(os.path.dirname(__file__) + '/libbitsandbytes.so')
  File "/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes.so: undefined symbol: __fatbinwrap_38_cuda_device_runtime_compute_75_cpp1_ii_8b1a5d37
```

Hi, I have encountered similar questions to #5 . I have tested with TeslaT4 and RTX 2080Ti but both failed.

The environment are as follows:
```
# TeslaT4
Ubuntu 18.04.6, Tesla T4, cuda-10.1, driver vesion: 418.197.02, python=3.8, torch=1.8.1+cu101

# RTX 2080Ti
Ubuntu 20.04.3, RTX 2080Ti, cuda-10.1, driver version: 435.21, python=3.8, torch=1.8.1+cu101
```

**Comment by Zakeiswo** [comment]
Same problem on RTX 2080Ti

**Comment by TimDettmers** [comment]
Thank you for reporting this! These are common GPUs, so it would be great to fix this to help others. Could you please try to compile from source and post the printed environmental variables:
1. `git clone https://github.com/facebookresearch/bitsandbytes.git`
2. `cd bitsandbytes`
3. `make cuda10x`



To use the compiled version and make sure the error does still occur you need to install the library via `CUDA_VERSION=101 python setup.py install`.

If that does not work, could go through the steps in [how to compile from source](https://github.com/facebookresearch/bitsandbytes/blob/main/compile_from_source.md) and report the environmental variables that are printed or any other problems.

**Comment by SparkJiao** [comment]
Hi, thanks for you help very much!

For 2080Ti, I succeeded to run my model (ALBERT-xxlarge-v2) on 2 2080Ti GPUs with fairscale fully sharded data parallel.

It seems that the problem is caused becaused the nvcc toolkit is not installed on the server so I install the cuda-10.1 by myself.

But it does not work for TeslaT4. I can't make it successfully and the log is as follows:
```
(torch1.8-py3.8) jiaofangkai@amax:/home/share/jiaofangkai/bitsandbytes-037022e$ make cuda10x
ENVIRONMENT
============================
NVCC path: /home/share/jiaofangkai/cuda-10.1/bin/nvcc
GPP path: /usr/bin/g++
CUDA_HOME: /home/share/jiaofangkai/cuda-10.1
CONDA_PREFIX: /home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8
PATH: /home/share/jiaofangkai/cuda-10.1/bin:/home/jiaofangkai/tmux/bin:/home/share/jiaofangkai/cuda-10.1/bin:/home/jiaofangkai/tmux/bin:/home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/bin:/home/share/jiaofangkai/anaconda3/bin:/home/share/jiaofangkai/anaconda3/bin:/home/jiaofangkai/bin:/home/jiaofangkai/.local/bin:/home/share/jiaofangkai/anaconda3/condabin:/home/share/jiaofangkai/cuda-10.1/bin:/home/jiaofangkai/tmux/bin:/home/jiaofangkai/bin:/home/jiaofangkai/.local/bin:/home/share/jiaofangkai/anaconda3/condabin:/home/share/jiaofangkai/cuda-10.1/bin:/home/jiaofangkai/tmux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH: /home/share/jiaofangkai/cuda-10.1-lib/lib64:
============================
/home/share/jiaofangkai/cuda-10.1/bin/nvcc -gencode arch=compute_35,code=sm_35  -gencode arch=compute_37,code=sm_37  -gencode arch=compute_50,code=sm_50  -gencode arch=compute_52,code=sm_52  -gencode arch=compute_60,code=sm_60  -gencode arch=compute_61,code=sm_61  -gencode arch=compute_70,code=sm_70  -gencode arch=compute_72,code=sm_72  -gencode arch=compute_72,code=sm_72  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_75,code=sm_75 -Xcompiler '-fPIC' --use_fast_math -Xptxas=-v -dc /home/share/jiaofangkai/bitsandbytes-037022e/csrc/ops.cu /home/share/jiaofangkai/bitsandbytes-037022e/csrc/kernels.cu -I /home/share/jiaofangkai/cuda-10.1/include -I /home/share/jiaofangkai/bitsandbytes-037022e/csrc -I /home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/include -I /home/share/jiaofangkai/bitsandbytes-037022e/dependencies/cub -I /home/share/jiaofangkai/bitsandbytes-037022e/include -L /home/share/jiaofangkai/cuda-10.1/lib64 -lcudart -lcuda -lcublas -lcurand -lcusparse -L /home/share/jiaofangkai/anaconda3/envs/torch1.8-py3.8/lib --output-directory /home/share/jiaofangkai/bitsandbytes-037022e/cuda_build
In file included from /home/share/jiaofangkai/bitsandbytes-037022e/dependencies/cub/cub/device/../util_arch.cuh:36:0,
                 from /home/share/jiaofangkai/bitsandbytes-037022e/dependencies/cub/cub/device/../config.cuh:35,
                 from /home/share/jiaofangkai/bitsandbytes-037022e/dependencies/cub/cub/device/device_scan.cuh:40,
                 from /home/share/jiaofangkai/bitsandbytes-037022e/csrc/ops.cu:8:
/home/share/jiaofangkai/bitsandbytes-037022e/dependencies/cub/cub/device/../util_cpp_dialect.cuh:129:13: warning: CUB requires C++14. Please pass -std=c++14 to your compiler. Define CUB_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
   CUB_COMPILER_DEPRECATION(C++14, pass -std=c++14 to your compiler);
             ^
In file included from /usr/include/c++/5/type_traits:35:0,
                 from /home/share/jiaofangkai/bitsandbytes-037022e/include/Algo-Direct-Common.h:5,
                 from /home/share/jiaofangkai/bitsandbytes-037022e/include/Algo-Direct2.h:3,
                 from /home/share/jiaofangkai/bitsandbytes-037022e/include/BinSearch.h:11,
                 from /home/share/jiaofangkai/bitsandbytes-037022e/csrc/ops.cu:10:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
Makefile:57: recipe for target 'cuda10x' failed
make: *** [cuda10x] Error 1
```
It seems that the problem is due to the version of C++ complier? Do you have any suggestions?

**Comment by TimDettmers** [comment]
This should have been fixed in the newest version b3fe8a6d0f53e3e81a4a6bc7385ce86077abf690. Can you try both installing from pip and also compiling from source? If there are still problems, please reopen the issue with the printed environmental variables. Thank you!

**Comment by liesun1994** [comment]
Same problem in GTX1080, with CUDA 101

**Comment by borzunov** [comment]
I had the same issue with GTX 0180 and CUDA 10.1. As mentioned above, the commands for rebuilding from source helped:

```bash
git clone https://github.com/facebookresearch/bitsandbytes.git
cd bitsandbytes
make cuda10x
```
