### ISSUE TITLE
Support for Tesla Architecture

### ISSUE THREAD

**Issue by nbroad1881** [facebookresearch/bitsandbytes#4]
First of all, great work!

Secondly, I can see that you specify that Maxwell Architecture is necessary, and I am wondering if 

1. it's possible to do 8-bit optimization on Tesla Architecture
2. there are plans to implement it

I ask because Kaggle and Colab notebooks use Tesla Architectures (P100, K80), and I'm sure those communities, myself included, would be interested in using bitsandbytes

**Comment by SirRob1997** [comment]
Wanted to try bitsandbytes using Tesla V100's and was getting this error message when running

```
wget https://gist.githubusercontent.com/TimDettmers/1f5188c6ee6ed69d211b7fe4e381e713/raw/4d17c3d09ccdb57e9ab7eca0171f2ace6e4d2858/check_bnb_install.py && python check_bnb_install.py
```

```Python
Traceback (most recent call last):
  File "check_bnb_install.py", line 1, in <module>
    import bitsandbytes as bnb
  File "/miniconda/envs/pytorch_env/lib/python3.7/site-packages/bitsandbytes/__init__.py", line 5, in <module>
    from .optim import adam
  File "/miniconda/envs/pytorch_env/lib/python3.7/site-packages/bitsandbytes/optim/__init__.py", line 5, in <module>
    from .adam import Adam, Adam8bit, Adam32bit
  File "/miniconda/envs/pytorch_env/lib/python3.7/site-packages/bitsandbytes/optim/adam.py", line 5, in <module>
    from bitsandbytes.optim.optimizer import Optimizer2State
  File "/miniconda/envs/pytorch_env/lib/python3.7/site-packages/bitsandbytes/optim/optimizer.py", line 6, in <module>
    import bitsandbytes.functional as F
  File "/miniconda/envs/pytorch_env/lib/python3.7/site-packages/bitsandbytes/functional.py", line 13, in <module>
    lib = ct.cdll.LoadLibrary(os.path.dirname(__file__) + '/libbitsandbytes.so')
  File "/miniconda/envs/pytorch_env/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/miniconda/envs/pytorch_env/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /miniconda/envs/pytorch_env/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes.so: undefined symbol: __fatbinwrap_38_cuda_device_runtime_compute_75_cpp1_ii_8b1a5d37
```

Is this related to this issue? and when can we see support for Tesla architectures?

**Comment by TimDettmers** [comment]
Hi @SirRob1997, this is a separate issue that occurred also for me too on CUDA 10.1. I opened a separate issue #5 could you leave there more details about what CUDA version you use. Thank you!

**Comment by david-hung** [comment]
I am getting this same issue. I'm using version 0.39

**Comment by babanty** [comment]
I am getting this same issue. I'm using version 0.41.1
GPU Tesla A10 (24GB) ubuntu 22.04.2 with https://github.com/oobabooga/text-generation-webui

```
ubuntu@a10-secondtry:~/Neural/text-generation-webui$ ./start_linux.sh
/home/ubuntu/Neural/text-generation-webui/installer_files/env/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/ubuntu/Neural/text-generation-webui/installer_files/env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
```

**Comment by babanty** [comment]
> I am getting this same issue. I'm using version 0.41.1 GPU Tesla A10 (24GB) ubuntu 22.04.2 with https://github.com/oobabooga/text-generation-webui
> 
> ```
> ubuntu@a10-secondtry:~/Neural/text-generation-webui$ ./start_linux.sh
> /home/ubuntu/Neural/text-generation-webui/installer_files/env/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
>   warn("The installed version of bitsandbytes was compiled without GPU support. "
> /home/ubuntu/Neural/text-generation-webui/installer_files/env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
> ```

The problem was with the Nvidia driver. Reinstalling to the latest version helped.
